// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpwf0pjsZ1AprP-fNYHKmzk4-ZeYoN3Ws',
    appId: '1:376153272412:web:c8da1fae97cf3216043699',
    messagingSenderId: '376153272412',
    projectId: 'foodsavior-792ee',
    authDomain: 'foodsavior-792ee.firebaseapp.com',
    storageBucket: 'foodsavior-792ee.appspot.com',
    measurementId: 'G-FF1M055TDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgReOquMZdeKaHvpxlyki2JfUmvm4sjbg',
    appId: '1:376153272412:android:f98c38314b3282de043699',
    messagingSenderId: '376153272412',
    projectId: 'foodsavior-792ee',
    storageBucket: 'foodsavior-792ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1NTf2IQhUKJHxxNT85uCuj_HQS83uyEE',
    appId: '1:376153272412:ios:13d7725ba732040f043699',
    messagingSenderId: '376153272412',
    projectId: 'foodsavior-792ee',
    storageBucket: 'foodsavior-792ee.appspot.com',
    iosClientId: '376153272412-sf2597v7c6ntg5785lcfa8jv6sb8o53f.apps.googleusercontent.com',
    iosBundleId: 'com.RateyHJ.foodSavior',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1NTf2IQhUKJHxxNT85uCuj_HQS83uyEE',
    appId: '1:376153272412:ios:543478546365b406043699',
    messagingSenderId: '376153272412',
    projectId: 'foodsavior-792ee',
    storageBucket: 'foodsavior-792ee.appspot.com',
    iosClientId: '376153272412-m4n3gg1uinh6j2qidrgds5ugt83uqkrl.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodSavior',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpwf0pjsZ1AprP-fNYHKmzk4-ZeYoN3Ws',
    appId: '1:376153272412:web:5a160c46e526105a043699',
    messagingSenderId: '376153272412',
    projectId: 'foodsavior-792ee',
    authDomain: 'foodsavior-792ee.firebaseapp.com',
    storageBucket: 'foodsavior-792ee.appspot.com',
    measurementId: 'G-4XS8FL8T0W',
  );

}