// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:food_savior/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(FoodItemAdapter());
    registerAdapter(FoodItemStatusAdapter());
    registerAdapter(FoodItemTypeAdapter());
    registerAdapter(UnitAdapter());
    registerAdapter(UsedFoodItemAdapter());
  }
}
